mango_platform_homepage:
    path:     /
    defaults: { _controller: MangoPlatformBundle:Index:index }

mango_platform_rent:
  path:    /location/{page}
  defaults: 
    _controller: MangoPlatformBundle:Rent:indexRent
  requirements:
    page: \d*

mango_platform_buy:
  path:    /achat/{page}
  defaults: 
    _controller: MangoPlatformBundle:Buy:indexBuy
  requirements:
    page: \d*

mango_platform_contact:
    path:     /contact
    defaults: { _controller: MangoPlatformBundle:Index:contact }

mango_platform_proposer:
    path:     /proposer
    defaults: { _controller: MangoPlatformBundle:Index:proposer }

mango_platform_rent_view:
  path:    /location/annonce/{id}
  defaults: 
    _controller: MangoPlatformBundle:Rent:view
  requirements:
    id: \d+

mango_platform_view_rent_mail:
  path: /achat/annonce/{id}/mail
  defaults: { _controller: MangoPlatformBundle:UserContact:viewMail}
  requirements:
    id: \d+

mango_platform_view_rent_phone:
  path: /achat/annonce/{id}/phone
  defaults: { _controller: MangoPlatformBundle:UserContact:viewPhone}
  requirements:
    id: \d+

mango_platform_view_buy:
  path:    /achat/annonce/{id}
  defaults: { _controller: MangoPlatformBundle:Buy:view }
  requirements:
    id: \d+

mango_platform_view_user_mail:
  path: /{id}/mail
  defaults: { _controller: MangoPlatformBundle:UserContact:viewMail}
  requirements:
    id: \d+

mango_platform_view_user_phone:
  path: /{id}/phone
  defaults: { _controller: MangoPlatformBundle:UserContact:viewPhone}
  requirements:
    id: \d+

mango_platform_user:
  path: /user/index
  defaults: { _controller: MangoPlatformBundle:User:index }
  requirements:
    id: \d+

mango_platform_user_info:
  path: /user/my-infos
  defaults: { _controller: MangoPlatformBundle:User:userInfos }

mango_platform_user_edit_info:
  path: /user/my-infos/edit
  defaults: { _controller: MangoPlatformBundle:User:editInfos }

mango_platform_addrent:
  path:    /add/rent
  defaults: { _controller: MangoPlatformBundle:AdvertManagement:addRent }

mango_platform_addbuy:
  path:    /add/buy
  defaults: { _controller: MangoPlatformBundle:AdvertManagement:addBuy }

mango_platform_edit_rent:
  path:    /edit/location/{id}
  defaults: { _controller: MangoPlatformBundle:AdvertManagement:editRent }
  requirements:
    id: \d+

mango_platform_edit_buy:
  path:    /edit/achat/{id}
  defaults: { _controller: MangoPlatformBundle:AdvertManagement:editBuy }
  requirements:
    id: \d+

mango_platform_delete:
  path:    /delete/{id}
  defaults: { _controller: MangoPlatformBundle:AdvertManagement:delete }
  requirements:
    id: \d+

mango_platform_admin_adverts:
  path: /admin/annonces
  defaults: { _controller: MangoPlatformBundle:Admin:adverts }

mango_platform_admin_users:
  path: /admin/users
  defaults: {_controller: MangoPlatformBundle:Admin:users}

mango_platform_admin_modos:
  path: /admin/modos
  defaults: {_controller: MangoPlatformBundle:Admin:modos}
