mango_platform_homepage:
    path:     /
    defaults: { _controller: MangoPlatformBundle:Index:index }

mango_platform_rent:
  path:    /location/{page}
  defaults: 
    _controller: MangoPlatformBundle:Rent:indexRent
  requirements:
    page: \d*

mango_platform_buy:
  path:    /achat/{page}
  defaults: 
    _controller: MangoPlatformBundle:Buy:indexBuy
  requirements:
    page: \d*

mango_platform_contact:
    path:     /contact
    defaults: { _controller: MangoPlatformBundle:Index:contact }

mango_platform_proposer:
    path:     /proposer
    defaults: { _controller: MangoPlatformBundle:Index:proposer }

mango_platform_rentview:
  path:    /location/annonce/{id}
  defaults: 
    _controller: MangoPlatformBundle:Rent:view
  requirements:
    id: \d+

mango_platform_view_buy:
  path:    /achat/annonce/{id}
  defaults: { _controller: MangoPlatformBundle:Buy:view }
  requirements:
    id: \d+

mango_platform_user:
  path: /user/index
  defaults: { _controller: MangoPlatformBundle:User:index }
  requirements:
    id: \d+

mango_platform_user_info:
  path: /user/my-infos
  defaults: { _controller: MangoPlatformBundle:User:userInfos }
  requirements:
    id: \d+

mango_platform_add:
  path:    /add
  defaults: { _controller: MangoPlatformBundle:User:add }

mango_platform_edit:
  path:    /edit/{id}
  defaults: { _controller: MangoPlatformBundle:User:edit }
  requirements:
    id: \d+

mango_platform_delete:
  path:    /delete/{id}
  defaults: { _controller: MangoPlatformBundle:User:delete }
  requirements:
    id: \d+

mango_platform_admin_adverts:
  path: /admin/annonces
  defaults: { _controller: MangoPlatformBundle:Admin:adverts }

mango_platform_admin_users:
  path: /admin/users
  defaults: {_controller: MangoPlatformBundle:Admin:users}

mango_platform_admin_modos:
  path: /admin/modos
  defaults: {_controller: MangoPlatformBundle:Admin:modos}
