<?php

namespace Mango\PlatformBundle\Repository;

/**
 * BuyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuyRepository extends \Doctrine\ORM\EntityRepository
{
}
