<?php

namespace Mango\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getRents($page, $nbPerPage){  //arguments pour la pagination
        $query = $this->createQueryBuilder('r')
                     ->where('r.published = 1')
                     ->leftJoin('r.image', 'i')  
                     ->addSelect('i')
                     ->leftJoin('r.city', 'c')  
                     ->addSelect('c')
                     ->leftJoin('r.type', 't')  
                     ->addSelect('t')
                     ->orderBy('r.date', 'DESC')
                     ->getQuery();

        $query->setFirstResult(($page-1)*$nbPerPage) //Commencement
              ->setMaxResults($nbPerPage); //Nb par page

        return new Paginator($query, true);
    }

    public function getRentsByUser($userId){  //Recherche par utilisateur
        $query = $this->createQueryBuilder('r')
                     ->where('r.userId = :user_id')
                     ->setParameter('user_id', $userId)
                     ->leftJoin('r.image', 'i')  
                     ->addSelect('i')
                     ->leftJoin('r.city', 'c')  
                     ->addSelect('c')
                     ->orderBy('r.date', 'DESC')
                     ->getQuery()
                     ->getResult();

        return $query;
    }

    public function findWithRegion($id){      //Récupération à partir de la région (moins de requête)
        $query = $this->createQueryBuilder('r')
                ->select('r, t, c, d, region')
                ->join('r.type', 't')
                ->join('r.city', 'c')
                ->join('c.departement', 'd')
                ->join('d.region', 'region')
                ->where('r.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getSingleResult();
        return $query;
    }
}
